### ISSUE TITLE
Allow destination file name and directory to be configurable

### ISSUE THREAD

**Issue by aeisenberg** [franckLdx/uploaderExpress#4]
I would like the destination file name and directory to be configurable. This will make it easier to organize uploads and categorize them by file types. 

I see configuration as something like this:

```js
const uploaderMiddleware = uploaderExpress.middleware({
  maxSize: '1gb',
  uploadDir: './upload',
  type: 'json',
  createName: req => {
    return `${getUserName(req.path)}/photo-${getPhotoAlbumName(req.path)}.jpg`;
  },
});
```

`createName` is a new configuration option that is a function and accepts a request as a parameter. The return value is the name of the file to be saved. If no `createName` function is supplied, then behaviour is as before. It is up to the client to ensure that there are no name clashes. Maybe we can expose a function to create a random string of characters to be used by a client, though it's just as easy to use the `uuid` package.

And lastly, notice that you can specify that a file be placed in a sub-directory. If the directory doesn't exist yet, it will be created.

I can work on this if you think it is a good addition to your package. Thanks.

**Comment by franckLdx** [comment]
Hello,

  I think it could be usefull. If you want to work on this go ahead (no need to provide random string, uuid does the job).

Many thanks

**Comment by aeisenberg** [comment]
Done. See above. There were two failing tests for me that fail on master. It looks like they have something to do with running on mac vs windows. I didn't try to fix them. But the new tests I added are passing properly.

**Comment by aeisenberg** [comment]
Also, the implementation is slightly different from what I suggested above. I decided that it makes more sense to have two optional callbacls: one for the parent directory and one for the file name.

**Comment by aeisenberg** [comment]
Thanks!
